server:
  port: 4000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 124563
    url: jdbc:mysql://127.0.0.1:3306/arthas-user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none

